CREATE TABLE "participationRecordDB" (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `user_created` char(36) NULL,
  `date_created` datetime NULL,
  `user_updated` char(36) NULL,
  `date_updated` datetime NULL,
  `registrationId` integer NOT NULL, 
  `activityId` integer NOT NULL, 
  `state` varchar(20) DEFAULT 'confirmed',
  `items` json NOT NULL,
  `totalAmount` decimal(10,2) NOT NULL,
  `discountAmount` decimal(10,2) DEFAULT 0,
  `finalAmount` decimal(10,2) NOT NULL,
  `paidAmount` decimal(10,2) DEFAULT 0,
  `needReceipt` boolean DEFAULT false,
  `receiptNumber` varchar(50) NULL,
  `receiptIssued` boolean DEFAULT false,
  `receiptIssuedAt` datetime NULL,
  `receiptIssuedBy` varchar(100) NULL,
  `accountingState` varchar(20) DEFAULT 'pending',
  `accountingDate` datetime NULL,
  `accountingBy` varchar(100) NULL,
  `accountingNotes` text NULL,
  `paymentState` varchar(20) DEFAULT 'unpaid',
  `paymentMethod` varchar(20) NULL,
  `paymentDate` datetime NULL,
  `paymentNotes` text NULL,
  `notes` text NULL,
  `createdAt` varchar(255) NULL,
  `updatedAt` varchar(255) NULL,
  CONSTRAINT `participationrecorddb_user_created_foreign` FOREIGN KEY (`user_created`) REFERENCES `directus_users` (`id`),
  CONSTRAINT `participationrecorddb_user_updated_foreign` FOREIGN KEY (`user_updated`) REFERENCES `directus_users` (`id`)
);
