CREATE TABLE "directus_users" (
    "id" char(36) NOT NULL,
    "first_name" varchar(50),
    "last_name" varchar(50),
    "email" varchar(128),
    "password" varchar(255),
    "location" varchar(255),
    "title" varchar(50),
    "description" text,
    "tags" json,
    "avatar" char(36),
    "language" varchar(255) DEFAULT null,
    "tfa_secret" varchar(255),
    "status" varchar(16) NOT NULL DEFAULT 'active',
    "role" char(36),
    "token" varchar(255),
    "last_access" datetime,
    "last_page" varchar(255),
    "provider" varchar(128) NOT NULL DEFAULT 'default',
    "external_identifier" varchar(255),
    "auth_data" json,
    "email_notifications" boolean DEFAULT '1',
    "appearance" varchar(255),
    "theme_dark" varchar(255),
    "theme_light" varchar(255),
    "theme_light_overrides" json,
    "theme_dark_overrides" json,
    "text_direction" varchar(255) NOT NULL DEFAULT 'auto',
    PRIMARY KEY ("id"),
    FOREIGN KEY ("role") REFERENCES "directus_roles" ("id") ON DELETE SET NULL
);