#!/bin/bash

echo "🧪 測試雙後端 JoinRecord 服務"
echo "================================="

echo ""
echo "📋 雙後端架構說明："
echo "- Directus 後端: ./client/src/services/joinRecordService.js"
echo "- Rust 後端:     ./client/src/rustServices/rustJoinRecordService.js"
echo "- 適配器:        ./client/src/adapters/serviceAdapter.js"

echo ""
echo "🔄 服務適配器功能："
echo "- 自動切換後端 (directus ↔ axum)"
echo "- 錯誤自動降級"
echo "- 統一的 API 接口"

echo ""
echo "📝 相同的 CRUD 方法："
echo "✅ createParticipationRecord()"
echo "✅ getAllParticipationRecords()"
echo "✅ getParticipationRecordById()"
echo "✅ getParticipationRecordsByRegistrationId()"
echo "✅ getParticipationRecordsByActivityId()"
echo "✅ updateParticipationRecord()"
echo "✅ deleteParticipationRecord()"
echo "✅ saveRecord()"

echo ""
echo "🎯 使用方式："
echo ""
echo "// 方式 1: 通過 serviceAdapter 直接調用"
echo "import { serviceAdapter } from './adapters/serviceAdapter.js';"
echo "const result = await serviceAdapter.createParticipationRecord(data);"
echo ""
echo "// 方式 2: 通過服務訪問器"
echo "const joinService = serviceAdapter.joinRecordService;"
echo "const result = await joinService.createParticipationRecord(data);"
echo ""
echo "// 方式 3: 手動切換後端"
echo "serviceAdapter.switchBackend('axum');    // 切換到 Rust"
echo "serviceAdapter.switchBackend('directus'); // 切換到 Directus"

echo ""
echo "🚀 雙後端已準備就緒！"
